import { Inter } from 'next/font/google';

import { MainLayout } from '@/components';

import type { Metadata } from 'next';

import './globals.css';

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      {/* <body> */}
      <body className={`${inter.className} ${inter.variable}`}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
