import { Inter } from 'next/font/google';
import localFont from 'next/font/local';

import { MainLayout } from '@/components';

import type { Metadata } from 'next';

import './globals.css';

const nanumBrushScriptRegular = localFont({
  src: '../assets/font/NanumBrushScript-Regular.ttf',
  variable: '--font-nanum-brush-script-regular',
});

const nanumPenScriptRegular = localFont({
  src: '../assets/font/NanumPenScript-Regular.ttf',
  variable: '--font-nanum-pen-script-regular',
});

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${inter.className} ${inter.variable} ${nanumBrushScriptRegular.variable} ${nanumPenScriptRegular.variable} bg-black`}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
